spring.application.name=ATS

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/ATS
spring.datasource.username=postgres
spring.datasource.password=1234567890
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
server.port=9090
jwt.secret=super-long-256-bit-secret-key-that-never-changes-123456
